### ISSUE TITLE
'makeFrameMosaic' and 'makeKymographC' are missing 'FLAGS' fields

### ISSUE THREAD

**Issue by Fouga** [wiggins-lab/SuperSegger#22]
I am trying to follow http://mtshasta.phys.washington.edu/website/tutorials/ssotutorial/trySuperSegger.html and to use makeFrameMosaic and makeKymographC functions. However, I get several errors like: Reference to non-existent field 'name of _the_ field'. 

Could you please provide fields for the FLAGS structure so I can can pass them to these functions?

**Comment by pawiggins** [comment]
Hi Natalia:

Ok… I fixed makeFrameMosaic and makeKymographC so they populate these new required fields in FLAGS when not FLAGS structure is passed. (I.e. if you wish to call these commands from the command line.)

At some point I’ll document the fields.

—PAW

**Comment by pawiggins** [comment]
FLAGS is a structure that controls how the multichannel images are displayed in composite images. The idea was to have a consistent way of supplying all the parameters required to make the image so that kymographs and frame mosaics would match what you see in the field of view. 

FLAGS is used in the following functions:
trainingConstants/makeTrainingData.m
trainingConstants/showSegRuleGUI.m
trainingConstants/showSegRule.m
trainingConstants/trainingGui.m
trainingConstants/updateTrainingImage.m
trainingConstants/updateTrainingImageTrain.m
viz/editSegmentsGui.m
viz/fixFlags.m
viz/intLoadDataViewer.m
viz/intMakeMultiChannel.m
viz/makeCellMovie.m
viz/makeFrameMosaic.m
viz/makeFrameStripeMosaic.m
viz/makeKymographC.m
viz/makeKymoMosaic.m
viz/shouldUseErrorFiles.m
viz/showSeggerImage.m
viz/superSeggerViewerGui.m

Fields in FLAGS:
-----------------------
% show legend?
             legend: 1

% controls where cells are labeled by cell or region IDs
          cell_flag: 1

% Each channel can be viewed in log intensity instead of intensity. Set these to true for channels where you want log intensity
           log_view: [0 0 0 0 0 0 0 0 0 0]   

% To see cell pixel outlines, set to true
       Outline_flag: 0

% Show composite versus single channel image
          composite: 0


% show filtered or unfiltered image for each channel
               filt: [0 0 0 0 0 0 0 0 0 0]

% When viewing a single channel (not in composite mode which shows a composite of all included channels), is the phase shown?
         phase_flag: [1 1 1 1 1 1 1 1 1 1]

% overall weight of each channel in the composite image. Defined on the interval [0,1]
              level: [0.5000 0.5000 0.5000 0.5000 0.5000 0.5000 0.5000 0.5000 0.5000 0.5000]

% set the out max and min for each channel
            lut_min: [NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN]
            lut_max: [NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN]

% in a composite image, which channels to include
            include: [1 1 1 1 1 1 1 1 1 1]

% is the LUT automatic or manual
         manual_lut: [0 0 0 0 0 0 0 0 0 0]

% whether to use autoscale relative to the current frame of relative to all frames in the time-lapse. (this is important for frame mosaics so that image background level is consistent between frames.
           gbl_auto: [0 0 0 0 0 0 0 0 0 0]

% Are foci shown? 
             s_flag: [0 0 0 0 0 0 0 0 0 0]

% Are foci scores shown?
        scores_flag: [0 0 0 0 0 0 0 0 0 0]

% show cell poles
             p_flag: 0

% Tight flag — controls how image is shown… can’t remember details… probably no longer used.
             T_flag: 0

% Show cells are colored regions
             P_flag: 1

% Show region scores
       regionScores: 0

% Show cell/region IDs
            ID_flag: 0             

% Controls which channel is being shown.
             f_flag: 0

% Allows multiple frames to be viewed simultaneously… probably doesn’t still work.
             m_flag: 0

% Historical / no longer used / not sure
        phase_level: 1
          lyse_flag: 0
             c_flag: 1
	e_flag: 0
          autoscale: 0

% use in training and segment editing etc.
            useSegs: 0
          showLinks: 0
        showMothers: 0
      showDaughters: 0
    colored_regions: 0
         edit_links: 0
